FROM node:14.10.1-alpine

# shell script
RUN mkdir /app

# RUN chown -R 1000:1000 /app

# RUN npm install -g typescript
# RUN npm install reflect-metadata --save
# RUN npm install typeorm --save
# RUN npm install @types/node --save-dev
# RUN cd /app
# RUN pwd
# RUN ls
# RUN echo "CD app"
# RUN cd app
# RUN echo "LS app"
# RUN ls app
RUN npm install
RUN npm install -g typescript
